name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.0
      - name: The Determinate Nix Installer
        uses: DeterminateSystems/nix-installer-action@v14
      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: Get Mathlib cache
        run: nix-shell --run "lake exe cache get"
      - name: Build vc tool
        run: nix-shell --run "cd vc; stack --nix build"
      - name: Build Lean files
        run: nix-shell --run "lake build"
